### ISSUE TITLE
Can't call methods that require UInt64 arguments

### ISSUE THREAD

**Issue by ryuslash** [retroj/dbus2-egg#4]
Trying to call a method requiring a UInt64 argument is causing me some trouble. When I try to pass along an argument I got from a signal which is supposed to be UInt64 I get the error:

    Type of message, '(d)', does not match expected type '(t)'

When I try it using a normal integer value, I get basically the same error, except I get a different type description:

    Type of message, '(i)', does not match expected type '(t)'

The type descriptor `(d)` means `double`, `(t)` means `uint64` and `(i)` means `int32`. According to the documentation there is no conversion from any type to UInt64, and it converts anything too big to be an Int32 to a Double.

**Comment by retroj** [comment]
moved to https://github.com/ec1oud/dbus-egg/issues/4
